import type { Payroll } from "../payroll.type";
import { PayrollStatusBadge } from "./PayrollStatusBadge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Clock, Receipt, User, DollarSign, Calculator } from "lucide-react";

interface PayrollDetailModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  payroll: Payroll | null;
}

export function PayrollDetailModal({
  open,
  onOpenChange,
  payroll,
}: PayrollDetailModalProps) {
  if (!payroll) return null;

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      maximumFractionDigits: 0,
    }).format(val);
  };

  const getMonthName = (m: number) => {
    const dates = [
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
    ];
    return dates[m - 1] || m;
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-160 max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="text-xl font-bold">Payroll Breakdown</DialogTitle>
            <PayrollStatusBadge status={payroll.status} />
          </div>
          <DialogDescription>
            Detailed salary calculation for period <span className="font-semibold text-slate-900 dark:text-slate-100">{getMonthName(payroll.month)} {payroll.year}</span>.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-2">
          {/* Employee Header Info */}
          <div className="p-4 bg-slate-50 dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-blue-100 dark:bg-blue-950 text-blue-600 dark:text-blue-400 rounded-lg">
                <User className="w-5 h-5" />
              </div>
              <div>
                <p className="font-bold text-sm text-slate-900 dark:text-slate-100">
                  {payroll.employee_name}
                </p>
                <p className="text-xs text-slate-500 font-mono">{payroll.employee_code}</p>
              </div>
            </div>

            <div className="text-right">
              <p className="text-xs text-slate-500">Generated By</p>
              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300 font-mono">
                {payroll.generated_by_email}
              </p>
            </div>
          </div>

          {/* Earnings Breakdown */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center">
              <DollarSign className="w-4 h-4 mr-1 text-emerald-600" />
              Earnings Breakdown
            </h4>

            <div className="bg-white dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 p-4 space-y-3">
              {/* Basic Salary */}
              <div className="flex justify-between items-center text-sm py-1 border-b border-slate-100 dark:border-slate-900">
                <span className="font-medium text-slate-700 dark:text-slate-300">Basic Base Salary</span>
                <span className="font-mono font-bold text-slate-900 dark:text-slate-100">
                  {formatCurrency(payroll.basic_salary)}
                </span>
              </div>

              {/* Overtime Details */}
              <div className="py-1 space-y-1.5 border-b border-slate-100 dark:border-slate-900">
                <div className="flex justify-between items-center text-sm">
                  <span className="font-medium text-slate-700 dark:text-slate-300 flex items-center">
                    <Clock className="w-3.5 h-3.5 mr-1.5 text-blue-500" />
                    Overtime Pay Total ({payroll.overtime_details.length} logs)
                  </span>
                  <span className="font-mono font-bold text-emerald-600 dark:text-emerald-400">
                    +{formatCurrency(payroll.overtime_total)}
                  </span>
                </div>
                {payroll.overtime_details.length > 0 && (
                  <div className="pl-5 space-y-1">
                    {payroll.overtime_details.map((ot) => (
                      <div key={ot.id} className="flex justify-between text-xs text-slate-500">
                        <span>
                          {new Date(ot.date).toLocaleDateString("en-GB")} ({ot.hours} hrs)
                        </span>
                        <span className="font-mono">{formatCurrency(ot.amount)}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Reimbursements Details */}
              <div className="py-1 space-y-1.5">
                <div className="flex justify-between items-center text-sm">
                  <span className="font-medium text-slate-700 dark:text-slate-300 flex items-center">
                    <Receipt className="w-3.5 h-3.5 mr-1.5 text-amber-500" />
                    Reimbursements Total ({payroll.reimbursement_details.length} claims)
                  </span>
                  <span className="font-mono font-bold text-emerald-600 dark:text-emerald-400">
                    +{formatCurrency(payroll.reimbursement_total)}
                  </span>
                </div>
                {payroll.reimbursement_details.length > 0 && (
                  <div className="pl-5 space-y-1">
                    {payroll.reimbursement_details.map((rb) => (
                      <div key={rb.id} className="flex justify-between text-xs text-slate-500">
                        <span>{rb.title}</span>
                        <span className="font-mono">{formatCurrency(rb.amount)}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Gross Total */}
              <div className="flex justify-between items-center text-sm pt-2 font-bold border-t border-slate-200 dark:border-slate-800">
                <span className="text-slate-900 dark:text-slate-100">Total Gross Salary</span>
                <span className="font-mono text-emerald-600 dark:text-emerald-400">
                  {formatCurrency(payroll.gross_salary)}
                </span>
              </div>
            </div>
          </div>

          {/* Deductions Breakdown */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center">
              <Calculator className="w-4 h-4 mr-1 text-rose-600" />
              Deductions Breakdown
            </h4>

            <div className="bg-white dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800 p-4 space-y-3">
              {/* Income Tax */}
              <div className="flex justify-between items-center text-sm py-1 border-b border-slate-100 dark:border-slate-900">
                <span className="font-medium text-slate-700 dark:text-slate-300">
                  Income Tax ({payroll.tax_percentage}%)
                </span>
                <span className="font-mono font-bold text-rose-600 dark:text-rose-400">
                  -{formatCurrency(payroll.tax)}
                </span>
              </div>

              {/* Other Deductions */}
              {payroll.other_deduction > 0 && (
                <div className="flex justify-between items-center text-sm py-1">
                  <div>
                    <span className="font-medium text-slate-700 dark:text-slate-300">Other Deduction</span>
                    {payroll.other_deduction_note && (
                      <p className="text-xs text-slate-500">{payroll.other_deduction_note}</p>
                    )}
                  </div>
                  <span className="font-mono font-bold text-rose-600 dark:text-rose-400">
                    -{formatCurrency(payroll.other_deduction)}
                  </span>
                </div>
              )}

              {/* Net Take Home */}
              <div className="flex justify-between items-center text-base pt-3 font-extrabold border-t border-slate-200 dark:border-slate-800">
                <span className="text-slate-900 dark:text-slate-100">Net Take-Home Salary</span>
                <span className="font-mono text-blue-600 dark:text-blue-400">
                  {formatCurrency(payroll.net_salary)}
                </span>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
